- name: Deploy to Server
  uses: appleboy/ssh-action@v1.0.3

  env:
    DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

  with:
    host: ${{ secrets.SERVER_IP }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      set -e

      echo "🚀 Starting Deployment"

      if [ -z "$DEPLOY_PATH" ]; then
        echo "❌ DEPLOY_PATH missing"
        exit 1
      fi

      cd $DEPLOY_PATH

      echo "📥 Pulling code"
      git pull origin main

      echo "📦 Installing PHP dependencies"
      composer install --no-dev --optimize-autoloader

      echo "🔐 Fixing permissions"
      chmod -R 775 storage bootstrap/cache

      echo "⚙️ Running migrations"
      php artisan migrate --force

      echo "🧹 Clearing cache"
      php artisan config:clear
      php artisan cache:clear
      php artisan view:clear

      echo "⚡ Optimizing"
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache

      echo "✅ Deployment Done"