name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, curl, zip, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-progress --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install NPM dependencies and build assets
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -ex

            echo "🚀 Starting Deployment"

            if [ -z "$DEPLOY_PATH" ]; then
              echo "❌ DEPLOY_PATH missing"
              exit 1
            fi

            cd $DEPLOY_PATH

            git pull origin main

            composer install --no-dev --optimize-autoloader

            chmod -R 775 storage bootstrap/cache

            php artisan migrate --force

            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "✅ Deployment Done"